version: "3"
services:
  db:
    image: mysql:5.7
    expose:
      - "3306"
    ports:
      - "3307:3306"
    env_file:
      - ./.env.development
    volumes:
      - db_data:/var/lib/mysql
    container_name: tasks-db
  api:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile.dev
      context: ./
    volumes:
      - ./:/usr/app/
    environment:
      - NODE_ENV=development
    expose:
      - "3000"
    ports:
      - "3000:3000"
    container_name: tasks-api
    entrypoint: ./development-entry.sh
    command: [/usr/app/development-entry.sh]
volumes:
  db_data: {}
