const MYSQL_ROOT_PASSWORD = `MYSQL_ROOT_PASSWORD`;
const MYSQL_USER = `MYSQL_USER`;
const MYSQL_DATABASE = `MYSQL_DATABASE`;
const MYSQL_PASSWORD = `MYSQL_PASSWORD`;
const AWS_ACCESS_KEY_ID = `AWS_ACCESS_KEY_ID`;
const AWS_SECRET_ACCESS_KEY = `AWS_SECRET_ACCESS_KEY`;
const AWS_S3_REGION = `AWS_S3_REGION`;
const AWS_S3_BUCKET_NAME = `AWS_S3_BUCKET_NAME`;

export {
    MYSQL_ROOT_PASSWORD,
    MYSQL_USER,
    MYSQL_DATABASE,
    MYSQL_PASSWORD,
    AWS_ACCESS_KEY_ID,
    AWS_SECRET_ACCESS_KEY,
    AWS_S3_REGION,
    AWS_S3_BUCKET_NAME
}